### ISSUE TITLE
Handle subscription ACKs from the server correctly

### ISSUE THREAD

**Issue by magiconair** [gopcua/opcua#369]
The short story is that we should keep track of the `PublishResponse`s ids we are ACK'ing and ignore if the server tells us to ACK a message twice.

This is a follow-up of #337 and the partial fix in #336.

**Comment by unknownet** [comment]
I think I understand where is the confusion.
I am not 100% sure but that would explain the problem.

`SubscriptionAcknowledgement` is not meant to tell the server that the client recieved the `AvailableSequenceNumbers`.
In fact I suppose in our case `AvailableSequenceNumbers` is irrelevant, It's probably usefull when you can have a multiple parrallel publish for the same `SubscriptionID`.
So that the subscription knows how many publish are waiting on server side to determine if it should spawn more parrallel publish dynamically.

I believe `SubscriptionAcknowledgement` is meant to tell the server that the client actually got the `publishResponse` with a given `SequenceNumber`.
And the `Results` tell the client if the `Acknowlegement`s was expected and recieved.

For instance with a single synchronous `publish` loop, acknowledgment array should not exceed one `SequenceNumber` at a time.
