### ISSUE TITLE
Bounty offer for looking into #368 and #376

### ISSUE THREAD

**Issue by dtoubelis** [gopcua/opcua#384]
May we offer you a bounty for resolving #368 and #376? These are two important issues for us and quite urgent.

**Comment by magiconair** [comment]
Hi Dmitri, thank you for reaching out. 

I cannot speak for the other contributors but I’d be willing to throw in some extra hours if you make a donation to something that makes the world a better place. My list includes in no particular order

* GoBridge - https://github.com/gobridge/about-us/blob/master/README.md
* Fridays for Future
* The International Red Cross
* Médecins Sans Frontières
* Greenpeace 

Or something else that you think is worthwhile - maybe something more local to you. 

To other contributors: please feel free provide your opinion as well. 

Please note that we will fix them eventually but I’m quite busy with hiring, day job and personal things. If you’re OK with making a donation I will throw in some evenings and night shifts to push this forward. 

So the most helpful thing you can do is to test the changes and provide feedback on the issue so that we see who needs this fix. 

But again: thank you for reaching out and welcome to the community ❤️

**Comment by dtoubelis** [comment]
Thanks. I've sent $200 to the first one on the list.

**Comment by dtoubelis** [comment]
Hi, is there any progress?

**Comment by magiconair** [comment]
Not yet. Injured my foot last week and got high workload at day job.

**Comment by magiconair** [comment]
@dtoubelis can you have a look at xxx and start testing that? It does not address the race condition yet but I need to check whether that is still relevant after the refactoring. 

Sorry, meant #385

**Comment by magiconair** [comment]
Hi @dtoubelis can we consider this closed?

**Comment by magiconair** [comment]
Maybe try with v0.2.1 which I've just released.

**Comment by dtoubelis** [comment]
We are no longer detecting any race conditions. so looks like it is resolved. Thank you for your help.
